-- ============================================================================
-- COVASOL Seed Data
-- 20 blog posts + 20 products
-- Sử dụng: mysql -u root -p covasol < database/seed-data.sql
-- ============================================================================

-- NOTE: Kiểm tra lại đường dẫn ảnh nếu cần. Các trường JSON (tags, keywords, feature_tags, highlights) đang ở dạng chuỗi JSON.

-- ============================================================================
-- BLOG POSTS (20)
-- Danh mục khớp bộ lọc client: Phát triển, AI & Tech, Thiết kế, Kinh doanh, Hướng dẫn
-- ============================================================================

INSERT INTO blog_posts (code, slug, title, subtitle, excerpt, content, image_url, category, tags, keywords, author_name, author_role, published_at, status, is_featured, created_at, updated_at) VALUES
('BLOG-001','xu-huong-react-2025','10 Xu hướng React.js 2025','Cập nhật frontend','Xu hướng Server Components, Streaming SSR, AI-assisted coding.','Nội dung demo về React 2025.','/assets/img/blog/react-trends.jpg','Phát triển','["React","Frontend"]','["react 2025","server components"]','Nguyễn Văn Minh','Senior Developer','2025-12-01 10:00:00','published',1,NOW(),NOW()),
('BLOG-002','nodejs-performance','Tối ưu hiệu suất Node.js','Enterprise tips','Connection pooling, caching, clustering.','Nội dung demo Node.js.','/assets/img/blog/nodejs-perf.jpg','Phát triển','["Node.js","Backend"]','["node performance"]','Trần Đức Anh','Tech Lead','2025-11-28 09:00:00','published',0,NOW(),NOW()),
('BLOG-003','microservices-guide','Microservices Architecture: Hướng dẫn','Từ monolith đến microservices','Chiến lược chuyển đổi an toàn.','Nội dung demo microservices.','/assets/img/blog/microservices.jpg','Phát triển','["Microservices","Architecture"]','["system design"]','Lê Hoàng Nam','Solution Architect','2025-11-25 14:30:00','published',0,NOW(),NOW()),
('BLOG-004','api-design-2025','RESTful API Design best practices','Thiết kế API chuẩn','Versioning, error handling, rate limit.','Nội dung demo API.','/assets/img/blog/api-design.jpg','Phát triển','["API","REST"]','["api design"]','Phạm Thị Hương','Backend Developer','2025-11-20 11:00:00','published',0,NOW(),NOW()),
('BLOG-005','ai-trong-dev','AI trong phát triển phần mềm','Tăng năng suất 40%','AI hỗ trợ code, test, doc.','Nội dung demo AI-dev.','/assets/img/blog/ai-dev.jpg','AI & Tech','["AI","Automation"]','["ai coding"]','Võ Minh Tuấn','AI Engineer','2025-12-03 08:00:00','published',0,NOW(),NOW()),
('BLOG-006','chatbot-doanh-nghiep','Chatbot AI cho doanh nghiệp','Từ ý tưởng đến triển khai','Quy trình xây chatbot đa kênh.','Nội dung demo chatbot.','/assets/img/blog/chatbot.jpg','AI & Tech','["Chatbot","NLP"]','["chatbot ai"]','Đặng Thị Lan','AI PM','2025-11-22 15:00:00','published',0,NOW(),NOW()),
('BLOG-007','ml-fintech','Machine Learning trong Fintech','Credit scoring & fraud','Use case ML tài chính.','Nội dung demo ML fintech.','/assets/img/blog/ml-fintech.jpg','AI & Tech','["ML","Fintech"]','["credit scoring"]','Nguyễn Hoàng Phúc','Data Scientist','2025-11-18 10:30:00','published',0,NOW(),NOW()),
('BLOG-008','computer-vision-ung-dung','Computer Vision thực chiến','Nhận dạng hình ảnh/video','Ứng dụng CV trong sản xuất, bán lẻ.','Nội dung demo CV.','/assets/img/blog/computer-vision.jpg','AI & Tech','["Computer Vision"]','["object detection"]','Trần Minh Khôi','ML Engineer','2025-11-15 09:00:00','published',0,NOW(),NOW()),
('BLOG-009','ui-ux-trends-2025','UI/UX Trends 2025','Thiết kế giao diện','Neumorphism, motion, accessibility.','Nội dung demo UI/UX.','/assets/img/blog/uiux-trends.jpg','Thiết kế','["UI/UX","Design"]','["ui ux trends"]','Lê Thị Mai','Lead Designer','2025-12-02 11:00:00','published',0,NOW(),NOW()),
('BLOG-010','design-system','Xây dựng Design System','Scalable design','Tokens, components, guidelines.','Nội dung demo design system.','/assets/img/blog/design-system.jpg','Thiết kế','["Design System"]','["component library"]','Nguyễn Thị Hà','Product Designer','2025-11-26 14:00:00','published',0,NOW(),NOW()),
('BLOG-011','mobile-first','Mobile-First Design','Responsive hiệu quả','Ưu tiên mobile, tối ưu hiệu năng.','Nội dung demo mobile-first.','/assets/img/blog/mobile-first.jpg','Thiết kế','["Mobile","Responsive"]','["mobile ux"]','Phạm Văn Đức','UX Designer','2025-11-12 10:00:00','published',0,NOW(),NOW()),
('BLOG-012','chuyen-doi-so-sme','Chuyển đổi số cho SME','Roadmap thực tế','Các bước nhỏ để bắt đầu.','Nội dung demo chuyển đổi số.','/assets/img/blog/digital-transformation.jpg','Kinh doanh','["SME","DX"]','["chuyển đổi số"]','Hoàng Minh Tâm','Business Consultant','2025-11-30 09:30:00','published',0,NOW(),NOW()),
('BLOG-013','roi-phan-mem','Tính ROI khi đầu tư phần mềm','Đánh giá hiệu quả','Cách đo ROI, payback.','Nội dung demo ROI.','/assets/img/blog/roi-software.jpg','Kinh doanh','["ROI","Investment"]','["business case"]','Trần Thị Linh','PM','2025-11-08 11:00:00','published',0,NOW(),NOW()),
('BLOG-014','saas-vs-custom','SaaS vs Custom Software','So sánh hai lựa chọn','Ưu nhược điểm, khi nào chọn.','Nội dung demo SaaS vs Custom.','/assets/img/blog/saas-custom.jpg','Kinh doanh','["SaaS","Custom"]','["buy vs build"]','Nguyễn Văn Hải','Consultant','2025-11-05 14:30:00','published',0,NOW(),NOW()),
('BLOG-015','docker-tutorial','Docker cho người mới','Container cơ bản','Cài đặt, Dockerfile, Compose.','Nội dung demo Docker.','/assets/img/blog/docker-tutorial.jpg','Hướng dẫn','["Docker","DevOps"]','["docker tutorial"]','Lê Văn Hùng','DevOps Engineer','2025-11-24 10:00:00','published',0,NOW(),NOW()),
('BLOG-016','nextjs-14-guide','Next.js 14 hướng dẫn','App Router & RSC','Data fetching, server actions.','Nội dung demo Next.js.','/assets/img/blog/nextjs-tutorial.jpg','Hướng dẫn','["Next.js","React"]','["nextjs 14"]','Phạm Minh Tuấn','Frontend Dev','2025-11-19 09:00:00','published',0,NOW(),NOW()),
('BLOG-017','git-workflow-team','Git Workflow cho team','Branching & review','Git Flow, PR, CI/CD.','Nội dung demo Git workflow.','/assets/img/blog/git-workflow.jpg','Hướng dẫn','["Git","Team"]','["git workflow"]','Võ Đình Khoa','Senior Dev','2025-11-14 11:30:00','published',0,NOW(),NOW()),
('BLOG-018','typescript-advanced','TypeScript Advanced Patterns','Type safety nâng cao','Generics, conditional types.','Nội dung demo TS.','/assets/img/blog/typescript-advanced.jpg','Hướng dẫn','["TypeScript"]','["advanced typescript"]','Nguyễn Thành Đạt','Senior Dev','2025-11-10 10:00:00','published',0,NOW(),NOW()),
('BLOG-019','aws-cost-optimization','AWS Cost Optimization','Tiết kiệm chi phí','Right-sizing, RIs, cleanup.','Nội dung demo AWS cost.','/assets/img/blog/aws-cost.jpg','Hướng dẫn','["AWS","Cloud"]','["cost optimization"]','Đinh Văn Long','Cloud Architect','2025-11-07 09:30:00','published',0,NOW(),NOW()),
('BLOG-020','cybersecurity-basics-2025','Cybersecurity Basics cho dev','Bảo mật web','OWASP Top 10, auth, HTTPS.','Nội dung demo security.','/assets/img/blog/cybersecurity.jpg','Hướng dẫn','["Security"]','["owasp"]','Bùi Quang Minh','Security Engineer','2025-11-03 11:00:00','published',0,NOW(),NOW());

-- ============================================================================
-- PRODUCTS (20)
-- ============================================================================

INSERT INTO products (code, slug, name, category, short_description, description, image_url, feature_tags, highlights, cta_primary_label, cta_primary_url, status, created_at, updated_at) VALUES
('PROD-001','virtual-assistant-platform','Virtual Assistant Platform','AI','Trợ lý AI đa kênh cho CSKH.','Nền tảng chatbot đa kênh tích hợp Zalo, FB, web widget.','/images/products/virtual-assistant.png','["AI","Chatbot"]','["Đa kênh","Dashboard realtime"]','Dùng thử miễn phí','/contact','active',NOW(),NOW()),
('PROD-002','ai-document-processor','AI Document Processor','AI','OCR & trích xuất dữ liệu.','Xử lý hóa đơn, hợp đồng với OCR + NLP.','/images/products/document-ai.png','["OCR","Automation"]','["OCR 99%","API dễ tích hợp"]','Xem demo','/contact','active',NOW(),NOW()),
('PROD-003','predictive-analytics-engine','Predictive Analytics Engine','AI','Dự đoán xu hướng kinh doanh.','ML dự báo doanh thu, phát hiện bất thường.','/images/products/predictive.png','["ML","Analytics"]','["Forecasting","Anomaly detection"]','Đặt lịch demo','/contact','active',NOW(),NOW()),
('PROD-004','manufacturing-mes','Manufacturing MES','MES','Điều hành sản xuất realtime.','Giám sát OEE, lệnh sản xuất, truy xuất nguồn gốc.','/images/products/mes.png','["MES","IoT"]','["OEE realtime","Mobile app tổ trưởng"]','Đặt lịch demo','/contact','active',NOW(),NOW()),
('PROD-005','iot-monitoring-system','IoT Monitoring System','IoT','Giám sát thiết bị & cảm biến.','Thu thập dữ liệu, cảnh báo thông minh, edge computing.','/images/products/iot.png','["IoT","Monitoring"]','["Alert rules","Edge gateway"]','Liên hệ tư vấn','/contact','active',NOW(),NOW()),
('PROD-006','quality-inspection-ai','Quality Inspection AI','AI','Camera AI kiểm tra lỗi sản phẩm.','Computer vision phát hiện lỗi 99.5%.','/images/products/quality-ai.png','["Computer Vision"]','["99.5% accuracy","1000+ sp/phút"]','Xem case study','/contact','active',NOW(),NOW()),
('PROD-007','erp-cloud-solution','ERP Cloud Solution','ERP','ERP cloud-native cho doanh nghiệp.','Tài chính, kho, CRM, nhân sự, báo cáo.','/images/products/erp.png','["ERP","Cloud"]','["Full modules","Đa chi nhánh"]','Yêu cầu báo giá','/contact','active',NOW(),NOW()),
('PROD-008','crm-smart','Smart CRM','CRM','Quản lý khách hàng thông minh.','Pipeline, automation, báo cáo bán hàng.','/images/products/crm.png','["CRM","Sales"]','["Automation","360 profile"]','Dùng thử','/contact','active',NOW(),NOW()),
('PROD-009','field-service-app','Field Service App','FSM','Quản lý kỹ thuật hiện trường.','Lịch giao việc, tracking, checklist.','/images/products/fsm.png','["Mobile","Offline"]','["Checklists","KPI theo thời gian"]','Book demo','/contact','active',NOW(),NOW()),
('PROD-010','inventory-optimizer','Inventory Optimizer','Supply Chain','Tối ưu tồn kho bằng ML.','Dự báo nhu cầu, đề xuất nhập/xuất.','/images/products/inventory.png','["Supply Chain","ML"]','["Giảm tồn kho","Tăng vòng quay"]','Xem demo','/contact','active',NOW(),NOW()),
('PROD-011','ecommerce-suite','E-commerce Suite','Ecom','Bộ giải pháp bán hàng online.','Storefront, thanh toán, vận chuyển, CRM.','/images/products/ecom.png','["Ecom","Payment"]','["Multi-channel","Marketing automation"]','Dùng thử','/contact','active',NOW(),NOW()),
('PROD-012','loyalty-platform','Loyalty Platform','Marketing','Chương trình khách hàng thân thiết.','Điểm thưởng, coupon, membership tiers.','/images/products/loyalty.png','["Loyalty","Marketing"]','["Omni-channel","Real-time points"]','Kích hoạt ngay','/contact','active',NOW(),NOW()),
('PROD-013','customer-data-platform','Customer Data Platform','Data','Hợp nhất dữ liệu khách hàng 360.','Ingest, identity resolution, segmentation.','/images/products/cdp.png','["CDP","Data"]','["360 view","Real-time segment"]','Xem demo','/contact','active',NOW(),NOW()),
('PROD-014','marketing-automation','Marketing Automation','Marketing','Tự động hóa email, SMS, push.','Journey builder, A/B test, analytics.','/images/products/marketing.png','["Automation","Campaign"]','["Journey","A/B test"]','Bắt đầu miễn phí','/contact','active',NOW(),NOW()),
('PROD-015','data-warehouse-cloud','Data Warehouse Cloud','Data','Kho dữ liệu cloud, BI-ready.','ETL/ELT, partition, RBAC, dashboard.','/images/products/dwh.png','["DWH","BI"]','["ETL","Cost control"]','Tư vấn miễn phí','/contact','active',NOW(),NOW()),
('PROD-016','realtime-analytics','Realtime Analytics','Data','Phân tích thời gian thực.','Stream processing, alerting, dashboards.','/images/products/realtime.png','["Streaming","Analytics"]','["Sub-second","Alert rules"]','Xem demo','/contact','active',NOW(),NOW()),
('PROD-017','helpdesk-suite','Helpdesk Suite','Support','Ticket, SLA, chatbot hỗ trợ.','Omnichannel helpdesk với AI assist.','/images/products/helpdesk.png','["Support","Chatbot"]','["SLA","Omnichannel"]','Dùng thử','/contact','active',NOW(),NOW()),
('PROD-018','booking-engine','Booking Engine','Services','Đặt lịch dịch vụ thông minh.','Calendar sync, payment, reminders.','/images/products/booking.png','["Booking","Payments"]','["Reminder","Calendar sync"]','Liên hệ','/contact','active',NOW(),NOW()),
('PROD-019','pos-retail','Retail POS','POS','Quản lý bán lẻ đa chi nhánh.','Bán hàng, kho, báo cáo, tích điểm.','/images/products/pos.png','["POS","Retail"]','["Offline/online","Loyalty"]','Demo nhanh','/contact','active',NOW(),NOW()),
('PROD-020','hrm-suite','HRM Suite','HR','Quản lý nhân sự end-to-end.','Tuyển dụng, chấm công, lương thưởng.','/images/products/hrm.png','["HR","Payroll"]','["Self-service","Mobile app"]','Xem demo','/contact','active',NOW(),NOW());

-- Hoàn tất seed dữ liệu mẫu.
