import { Router } from 'express';
import { authRouter } from './auth';
import { blogRouter } from './blog';
import { productRouter } from './products';
import { usersRouter } from './users';
import { reviewRouter } from './reviews';
import { analyticsRouter } from './analytics';
import { seasonalThemeRouter } from './seasonal-theme';
import { adminBlogRouter } from './admin/blog';
import { adminProductRouter } from './admin/products';
import { adminAnalyticsRouter } from './admin/analytics';
import { adminReviewRouter } from './admin/reviews';
import { adminUploadRouter } from './admin/uploads';
import { adminSystemLogsRouter } from './admin/system-logs';
import { adminSeasonalThemeRouter } from './admin/seasonal-themes';
import { requireAuth } from '../middleware/require-auth';

export const router = Router();

router.use('/auth', authRouter);
router.use('/blog', blogRouter);
router.use('/products', productRouter);
router.use('/users', usersRouter);
router.use('/reviews', reviewRouter);
router.use('/analytics', analyticsRouter);
router.use('/seasonal-theme', seasonalThemeRouter);
router.use('/admin/blog', requireAuth, adminBlogRouter);
router.use('/admin/products', requireAuth, adminProductRouter);
router.use('/admin/analytics', requireAuth, adminAnalyticsRouter);
router.use('/admin/reviews', requireAuth, adminReviewRouter);
router.use('/admin/uploads', requireAuth, adminUploadRouter);
router.use('/admin/system-logs', requireAuth, adminSystemLogsRouter);
router.use('/admin/seasonal-themes', requireAuth, adminSeasonalThemeRouter);
